#!/bin/sh /etc/rc.common

START=35
BASEDIR=/www/scada/modules

start() {
  local brand hostname ntp
  local ext=".gz"

  brand=$(cat /lib/genohm-scada/brand)
  # branding on first run
  [ -e "$BASEDIR/20-scripting.js$ext" ] && {
    hostname=$(uci get system.@system[0].hostname)

    mv "$BASEDIR/20-scripting.js$ext" "$BASEDIR/60-scripting.js$ext"

    [ "$hostname" = "LogicMachine" ] && {
      uci set system.@system[0].hostname="$brand"
      uci commit system

      echo "$brand" > /proc/sys/kernel/hostname
    }

    gunzip /www/scada/resources/language.js.gz
    gunzip /www/scada/modules/60-utilities.js.gz

    sed -i -e s/Touch/Smartphone/g -e s/Usermode/PC\\/Tablet/g /www/scada/resources/language.js
    sed -i -e s/brand/"$brand"/g /www/home.html

    sed -i -e 's/index:void 0/index:0/' /www/scada/modules/60-utilities.js

    gzip /www/scada/resources/language.js
    gzip /www/scada/modules/60-utilities.js

    [ "$brand" = "5500NAC" -o "$brand" = "5500SHAC" ] && ntp=clipsal || ntp=schneider

    uci delete system.ntp.server
    uci add_list system.ntp.server=0.$ntp.pool.ntp.org
    uci add_list system.ntp.server=1.$ntp.pool.ntp.org
    uci add_list system.ntp.server=2.$ntp.pool.ntp.org
    uci add_list system.ntp.server=3.$ntp.pool.ntp.org
    uci commit system
  }

  uci -q get apps.core.order >&- || {
    uci set apps.core.order='{"a.pctablet":1,"b.smartphone":2,"c.scheduler":3,"d.trends":4,"touch":5,"touch-config":6,"e.configurator":7,"fbeditor20":8}'
    uci commit apps
  }

  rm -f /lib/genohm-scada/plugins/modbus/profiles/UIO20.json
  sync
}
