#!/bin/sh /etc/rc.common

START=62
VSFTPD_KEY=/etc/vsftpd.key
VSFTPD_CRT=/etc/vsftpd.crt

vsftpd_ssl_config() {
printf "\n\
rsa_cert_file=/etc/vsftpd.crt\n\
rsa_private_key_file=/etc/vsftpd.key\n\
ssl_enable=YES\n\
allow_anon_ssl=YES\n\
force_local_data_ssl=NO\n\
force_local_logins_ssl=NO\n\
ssl_tlsv1=YES\n\
ssl_sslv2=NO\n\
ssl_sslv3=NO\n\
require_ssl_reuse=NO\n\
ssl_ciphers=HIGH\n" >> /etc/vsftpd.conf
}

vsftpd_config() {
  local cfg="$1"
  local enabled

  config_get enabled "$cfg" enabled

  [ "$enabled" = "1" ] && {
    mkdir -m 0755 -p /var/run/vsftpd
    service_start /usr/sbin/vsftpd
  }
}

start() {
  local realm="$(uci_get system.@system[0].hostname)"
  local mntdir ftpdir

  grep -q amatilinea /proc/device-tree/model && {
    sed -i 's#ftp:/.*#ftp:/mnt/local:/bin/false#' /etc/passwd
    mntdir=/mnt/local
  } || {
    ftpdir=/home/ftp
    mntdir=/data/ftp

    [ -L "$ftpdir" -o ! -e "$ftpdir" ] && {
      rm -f $ftpdir
      ln -sf $mntdir $ftpdir
    }
  }

  [ -e "$mntdir" ] || mkdir -m 0755 -p $mntdir
  chown ftp:ftp $mntdir

  grep -q ssl_enable /etc/vsftpd.conf || vsftpd_ssl_config

  [ -s "$VSFTPD_CRT" -a -s "$VSFTPD_KEY" ] || {
    rm -f "$VSFTPD_CRT"
    rm -f "$VSFTPD_KEY"
    /usr/sbin/px5g selfsigned -newkey rsa:2048 \
      -keyout "$VSFTPD_KEY" -out "$VSFTPD_CRT" \
      -subj /CN="${realm:-LogicMachine}"
  }

  config_load vsftpd
  config_foreach vsftpd_config vsftpd
}

stop() {
  service_stop /usr/sbin/vsftpd
}
