#!/bin/sh /etc/rc.common

STOP=10
START=50

SERVICE_USE_PID=1

start () {
	[ -z "$(ls /etc/crontabs/)" ] && exit 1
	cat /etc/crontabs/store/* > /etc/crontabs/root
	mkdir -p /var/spool/cron
	ln -s /etc/crontabs /var/spool/cron/ 2>/dev/null
	service_start /usr/sbin/crond -l 20 -c /etc/crontabs
}

stop() {
	service_stop /usr/sbin/crond
}

reload() {
	cat /etc/crontabs/store/* > /etc/crontabs/root
	touch /etc/crontabs
}
