#!/bin/sh /etc/rc.common

START=30
STOP=50

dropbear_start() {
  local enabled port nopass

  config_get_bool enabled "$1" enable 0
  config_get port "$1" port 22

  [ "$enabled" -eq 1 ] || return

  [ -e "/etc/dropbear" ] || {
    mkdir -p /etc/dropbear
    chown root /etc/dropbear
    chmod 0700 /etc/dropbear
  }

  # remote empty host keys
  for keytype in rsa ed25519; do
    key=/etc/dropbear/dropbear_${keytype}_host_key
    [ -f $key -a ! -s $key ] && rm $key
  done

  grep -q 'root:\*:' /etc/shadow && nopass="-s"
  dropbear -R -p $port -K 300 $nopass
}

start() {
  config_load dropbear
  config_foreach dropbear_start dropbear
}

stop() {
  killall dropbear
}
