#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

system_config() {
  local cfg="$1"
  local hostname timezone

  config_get hostname "$cfg" hostname 'LM'
  echo "$hostname" > /proc/sys/kernel/hostname

  config_get timezone "$cfg" timezone 'UTC'
  echo "$timezone" > /tmp/TZ

  date -k
}

start() {
  local rootdev

  mkdir -p /var/run
  mkdir -p /var/log
  mkdir -p /var/lock
  mkdir -p /var/state
  mkdir -p /tmp/.uci
  chmod 0700 /tmp/.uci
  touch /var/log/wtmp
  touch /var/log/lastlog
  touch /tmp/resolv.conf.auto
  ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf

  sh -c '. /lib/functions.sh; uci_apply_defaults'

  config_load system
  config_foreach system_config system

  service_start /sbin/syslogd -C16
  service_start /sbin/klogd

  killall -q hotplug2
  /sbin/hotplug2 --override --persistent \
    --set-rules-file /etc/hotplug2.rules \
    --set-coldplug-cmd /sbin/udevtrigger \
    --max-children 1 >/dev/null 2>&1 &

  # create /dev/root if it doesn't exist
  [ -e /dev/root -o -h /dev/root ] || {
    rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
    [ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
  }
}

stop() {
  service_stop /sbin/klogd
  service_stop /sbin/syslogd
}
