#!/bin/sh
# Arg: 1
# sysvinit-inittab - postinst
# run this on the target
if [ "x$D" = "x" ]; then
	tmp="38400;ttyS0"
	for i in $tmp
	do
		j=`echo ${i} | sed s/^.*\;//g`
		if [ -z "`cat /proc/consoles | grep ${j}`" ]; then
			sed -i /^.*${j}$/d /etc/inittab
		fi
	done
	kill -HUP 1
else
	if [ "38400;ttyS0" = "" ]; then
		exit 0
	else
		exit 1
	fi
fi