#!/bin/sh

# Script to manage the thmShow command
# This command show the current thm active device and the 
# status of the devices that have been configured.
#Usage: ./thmShow

cmd_file="/sys/firmware/THM/status"
info_file="/sys/firmware/THM/info"
cmd="THM_SHOW:S"

if [ ! -f $cmd_file ]; then
    echo "Unable to process the thmShow command."
    echo "The thm driver has not been loaded or the"
    echo "sys filesystem has not been mounted"
    exit 1 
fi

echo "$cmd" >$cmd_file
if [ "$?" -ne "0" ]; then
    echo "thmShow command error."
    echo "Maybe the thm library has not been loaded yet."
    exit 1 
else
    cat $info_file
fi

exit 0 
