#!/bin/sh
[ $# = 0 ] && exit

. /lib/functions.sh
. /lib/functions/network.sh

stop_proc() {
  local proc="$1"
  local pid="/var/run/$2.pid"

  [ -x "$proc" ] && {
    SERVICE_PID_FILE="$pid" \
    service_stop "$proc"
  }
}

interface="$1"
stop_interface() {
  local ifc="$1"
  local ifname

  [ "$ifc" = "$interface" -o "$interface" = "-a" ] && {
    config_get ifname "$ifc" ifname

    [ "$ifname" = "lo" ] && return

    stop_proc /usr/sbin/wpad wifi-$ifname
    stop_proc /sbin/udhcpc dhcp-$ifname
    ifconfig "$ifname" 0.0.0.0 down >/dev/null 2>&1
    remove_dns "$ifc"
    uci_revert_state network "$ifc"
  }
}

config_load network
config_foreach stop_interface interface
[ "$interface" = "-a" ] && sleep 1
